<?php
// FOR ALL
define('CONSUMER_KEY', YOUR_CONSUMER_KEY);
define('CONSUMER_SECRET', YOUR_CONSUMER_SECRET);
define('ACCESS_TOKEN', YOUR_ACCESS_TOKEN);
define('ACCESS_TOKEN_SECRET', YOUR_ACCESS_TOKEN_SECRET);
define('SLEEP_TIME_SEC', 60);
define('FOLLOW_UPPER_LIMIT', 20);

// FOR SEARCH
define('SEARCH_QUERRY', SEARCH_WORD);
define('SEARCH_CNT', 100);
define('TO_MAIL', YOUR_TO_MAIL);
define('FROM_MAIL', YOUR_FROM_MAIL);
define('SUBJECT', YOUR_MAIL_SUBJECT);
define('ERROR_MSG', YOUR_MAIL_ERROR_MSG);
